### ISSUE TITLE
Use bower for package management

### ISSUE THREAD

**Issue by anuja-joshi** [shidhincr/LookAround#17]
I recommend using bower for client side asset management as it makes dependency management easier. Also, it's the convention.

**Comment by shidhincr** [comment]
Agree.. It would be better if we change the Angular and Angular router load from bower packages

**Comment by sahilbhatia** [comment]
@shidhincr @anuja-joshi 

I am working on it. Will rebase and push the changes once you accept the pull request for issue #12 

Waiting for you to accept issue #12 as that includes changes for ngRoute.

**Comment by shidhincr** [comment]
@anuja-joshi @sahilbhatia I'll accept the PR now. The only problem is that, the changes for removing the `sensor` got removed when I merged the changes. So you might need to add that change again in your next PR.

**Comment by shidhincr** [comment]
#16 is merged

**Comment by sahilbhatia** [comment]
Thanks @shidhincr :smile:

**Comment by anuja-joshi** [comment]
@sahilbhatia will you be adding **bower_components** folder to git repo?

**Comment by sahilbhatia** [comment]
Yes @anuja-joshi , I am planning to push it to git. I know it will increase the repo size but I see the following advantages of adding it to git:

- Demo app is running on heroku (without the dependencies committed, the target server (e.g. Heroku) must run `bower install` to generate the dependencies)
- Deployment process will no longer be dependent on availability of Bower repository

@anuja-joshi @shidhincr What are your thougts on this?

**Comment by shidhincr** [comment]
@sahilbhatia I wouldn't rather do that. Because:

- It's always better to do the bower install ( on build time ), so that we get the dependencies updated, and will know about any breaking changes.
- For any new user who uses the app, it's better to do bower install on their machine rather than serving the whole bunch of files.
- If we start adding more dependencies, this will be a pain to see whole bunch of these files in the commit  history.

**Comment by anuja-joshi** [comment]
@sahilbhatia  I agree with approach suggested by @shidhincr ,
You can specify `bower` as dependency in `package.json`  and add `bower install` in `postinstall` section.
You can refer [this](http://xseignard.github.io/2013/02/18/use-bower-with-heroku/).

**Comment by sahilbhatia** [comment]
Fair enough, will not push bower_compnents to git. Instead, I will add bower as dependency to package.json as suggested by @anuja-joshi  above.
