### ISSUE TITLE
deepak

### ISSUE THREAD

**Issue by deepakgl** [shidhincr/LookAround#8]
i am trying to learn this app . It is beautifull app . but when i am running this on my localhost it is
providing me an error that the google api key is not the valid key . i have changed the key in the file where you include the google api link i.e in index.html

can you please tell me what is the reason behind the error ??

**Comment by shidhincr** [comment]
Could you please tell me the exact error you're getting ? A screenshot would be ideal.

Also, you loading the app from the http server right ?
